dataset_name: "shanghai"
without_background: True
seed: 42
device: "cuda"
root_path: "./data"
fe_name: "resnet18"
img_size: None
extract_blocks: "0,1,2,3,4"
estimator_name: "mvg"
estimator_loss: "none"

# dataloader params
batch_size: 32
num_workers: 2
epochs: 10
tta: 1

# trainer params
gpus: 1

# output settings
disable_progress_bar: False
verbose: True
